/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimeline: typeof import('./src/components/ActivityTimeline.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    CommentSection: typeof import('./src/components/CommentSection.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Topbar: typeof import('./src/components/layout/Topbar.vue')['default']
  }
}
