export const statusColorMap = {
  Planning: 'gray',
  'In Progress': 'blue',
  Completed: 'green',
  'On Hold': 'yellow',
  Cancelled: 'red',
  Open: 'gray',
  Working: 'blue',
  Blocked: 'red',
  Draft: 'gray',
  WIP: 'blue',
  'Ready for Approval': 'blue',
  'Awaiting Client Review': 'yellow',
  Approved: 'green',
  'Changes Requested': 'red',
  Low: 'gray',
  Medium: 'blue',
  High: 'yellow',
  Critical: 'red',
  Active: 'green',
  Inactive: 'gray',
  Suspended: 'red',
}
